name: Sync to Treehandmade Homepage

on:
  #   push:
  #     branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Template Repo
        uses: actions/checkout@v4

      - name: Set up Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone Target Repo (dev branch)
        run: |
          git clone --single-branch --branch dev https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/iCyanCorporation/treehandmade-homepage.git target-repo

      - name: Sync Selected Files
        run: |
          mkdir -p temp-sync
          rsync -av --files-from=.template-sync.txt ./ ./temp-sync/
          rsync -av --delete ./temp-sync/ ./target-repo/

      - name: Debug - Show git status after rsync
        run: |
          git status
          git diff --stat
        working-directory: target-repo

      - name: Commit and Push to Feature Branch
        id: commit_push
        working-directory: target-repo
        run: |
          git config --global --add safe.directory "$PWD"
          git fetch origin dev
          git checkout dev
          if [[ -n "$(git status --porcelain)" ]]; then
            git checkout -B sync-from-template
            git add .
            git commit -m "chore: sync from template repo"
            git push origin sync-from-template --force
            echo "changes_pushed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to sync."
            echo "changes_pushed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request in Target Repo
        if: steps.commit_push.outputs.changes_pushed == 'true'
        run: |
          gh pr create \
            --repo iCyanCorporation/treehandmade-homepage \
            --head sync-from-template \
            --base dev \
            --title "Sync from Template Repo" \
            --body "Automated sync from [nextjs-amplify-cms-template](https://github.com/iCyanCorporation/nextjs-amplify-cms-template)."
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        working-directory: target-repo
