name: Sync to Treehandmade Homepage

on:
  #   push:
  #     branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Template Repo
        uses: actions/checkout@v4
        with:
          ref: master # Ensures we are syncing from the master branch of the template

      - name: Set up Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone Target Repo (dev branch)
        uses: actions/checkout@v4
        with:
          repository: iCyanCorporation/treehandmade-homepage
          ref: dev
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: target-repo
          persist-credentials: true

      - name: Debug remotes in target-repo
        run: |
          cd target-repo
          git remote -v

      - name: Sync Selected Files
        run: |
          mkdir -p temp-sync
          rsync -av --files-from=.template-sync.txt ./ ./temp-sync/
          rsync -av --delete ./temp-sync/ ./target-repo/

      - name: Debug - Show git status after rsync
        run: |
          cd target-repo
          git status
          git diff --stat

      - name: Commit and Push to Feature Branch
        id: commit_push
        working-directory: target-repo
        run: |
          git config --global --add safe.directory "$PWD"
          echo "changes_pushed=false" > $GITHUB_OUTPUT
          echo "has_new_commits=false" >> $GITHUB_OUTPUT

          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Local changes detected after rsync."
            git checkout -B sync-from-template
            git add .
            git commit -m "chore: sync from template repo"
            echo "Pushing sync-from-template to origin..."
            git push --force origin sync-from-template
            echo "changes_pushed=true" >> $GITHUB_OUTPUT

            echo "Fetching latest state of dev and sync-from-template from remote..."
            git fetch origin dev sync-from-template

            echo "Checking for new commits on sync-from-template compared to origin/dev..."
            # Counts commits in origin/sync-from-template that are not in origin/dev
            # Need to ensure local sync-from-template is aligned with origin/sync-from-template for this comparison
            # The push ensures origin/sync-from-template is updated.
            # The fetch ensures origin/dev is updated.
            # We compare the pushed sync-from-template against the latest dev.
            commit_count=$(git rev-list --count origin/dev..origin/sync-from-template)
            
            if [[ "$commit_count" -gt 0 ]]; then
              echo "Found $commit_count new commit(s) on origin/sync-from-template compared to origin/dev."
              echo "has_new_commits=true" >> $GITHUB_OUTPUT
            else
              echo "No new commits found on origin/sync-from-template compared to origin/dev. PR will not be created."
            fi
          else
            echo "No local changes to sync after rsync."
          fi

      - name: Create Pull Request in Target Repo
        if: steps.commit_push.outputs.changes_pushed == 'true' && steps.commit_push.outputs.has_new_commits == 'true'
        working-directory: target-repo
        run: |
          gh pr create \
            --repo iCyanCorporation/treehandmade-homepage \
            --head sync-from-template \
            --base dev \
            --title "Sync from Template Repo" \
            --body "Automated sync from [nextjs-amplify-cms-template](https://github.com/iCyanCorporation/nextjs-amplify-cms-template)."
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
