name: Sync to Treehandmade Homepage

on:
  #   push:
  #     branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Template Repo
        uses: actions/checkout@v4
        with:
          ref: master # Ensures we are syncing from the master branch of the template

      - name: Set up Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone Target Repo (dev branch)
        run: |
          git clone --single-branch --branch dev https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/iCyanCorporation/treehandmade-homepage.git target-repo
          cd target-repo
          echo "Checking current branch in target-repo..."
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch is: $current_branch"
          if [ "$current_branch" != "dev" ]; then
            echo "Error: Failed to clone or checkout the 'dev' branch from the target repository (iCyanCorporation/treehandmade-homepage)." >&2
            echo "Please ensure the 'dev' branch exists on that repository and has at least one commit." >&2
            exit 1
          fi
          echo "'dev' branch successfully cloned and checked out in target-repo."
          cd ..

      - name: Sync Selected Files
        run: |
          mkdir -p temp-sync
          rsync -av --files-from=.template-sync.txt ./ ./temp-sync/
          rsync -av --delete ./temp-sync/ ./target-repo/

      - name: Debug - Show git status after rsync
        run: |
          git status
          git diff --stat
        working-directory: target-repo

      - name: Commit and Push to Feature Branch
        id: commit_push
        working-directory: target-repo
        run: |
          git config --global --add safe.directory "$PWD"
          # Work directly with the already cloned dev branch
          if [[ -n "$(git status --porcelain)" ]]; then
            git checkout -B sync-from-template
            git add .
            git commit -m "chore: sync from template repo"
            git push origin sync-from-template --force
            echo "changes_pushed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to sync."
            echo "changes_pushed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request in Target Repo
        if: steps.commit_push.outputs.changes_pushed == 'true'
        run: |
          gh pr create \
            --repo iCyanCorporation/treehandmade-homepage \
            --head sync-from-template \
            --base dev \
            --title "Sync from Template Repo" \
            --body "Automated sync from [nextjs-amplify-cms-template](https://github.com/iCyanCorporation/nextjs-amplify-cms-template)."
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        working-directory: target-repo
